### ISSUE TITLE
applyMicroClustering

### ISSUE THREAD

**Issue by mhimanshu11** [YosefLab/VISION#45]
Hi,
I am trying to work with applyMicroClustering method, and somehow I don't really understand the parameter "**cellsPerPartition**". As per the documentation, it should make cell pooling based on minimum of cellsPerPartition parameter, if I use say **cellsPerPartition= 10**, I have pooled cells of sizes more than 10 in some cases (see the output below)

---------------------------------------------------------------------------------------------------------
### macro_subclust <- VISION::applyMicroClustering(exprData= clusterData, cellsPerPartition=10, filterInput= var_genes)

    Computing a latent space for microclustering using PCA...
    Performing initial coarse-clustering...
    Further partitioning coarse clusters...
    Micro-pooling completed reducing 137 cells into 15 pools

###  sapply(macro_subclust, function(x) length(x))

  microcluster 1  microcluster 2  microcluster 3  microcluster 4  microcluster 5
             16                3              14               3              17
 microcluster 6  microcluster 7  microcluster 8  microcluster 9 microcluster 10
              5               6              14               1              12
microcluster 11 microcluster 12 microcluster 13 microcluster 14 microcluster 15
             11               3              11               6              15
### 
----------------------------------------------------------------------------------------------------------

**Further**, if I simply run the applyMicroClustering without any paramters, e.g, 
pools <- applyMicroClustering(scaled_counts, cellsPerPartition = 5) I get the following error: Error in exprData[gene_passes, ] : subscript out of bounds

**Comment by deto** [comment]
Hi @mhimahshu11 - thanks for the detailed report.

For the cluster sizes, it looks like we just weren't describing the parameter very well in the documentation.  It's more of a target cluster size - if you specify 10 cellsPerPartition, you'll end up with _around_ N/10 pools.  The reason its not a hard limit is that we didn't want to force micropools to merge cells across cell types/states just to hit the exact number.  I've updated the wording in the documentation so that it better reflects the purpose.

For the second issue, I think the problem is that the default filtering, prior to PCA, might not be returning any genes.  This is controlled by the filterInput and filterThreshold parameters.  In investigating your issue, I saw that the default threshold setting for applyMicroClustering was 20% (remove genes expressed in less than 20% of cells) - this is probably too high for many single cell datasets so I've lowered it to 5% (this is what the Vision constructor uses).  I've also added in some more error and diagnostic messages so if filtering is the issue, it should be more clear.  If you update and re-run, I think the error will be more informative.

Also, you might not want to use microclustering anyways for only 137 cells - that's already not very many  and it may get difficult to visualize patterns with much less.
