### ISSUE TITLE
Loading Seurat object

### ISSUE THREAD

**Issue by LVH10** [YosefLab/VISION#55]
Hi!

I am trying to use a Seurat object as input to create a Vision object as described [here](https://github.com/YosefLab/VISION/blob/master/vignettes/web_only/Seurat.Rmd). For the following step, I cannot get passed the error message.

vision.obj <- Vision(seurat.obj, signatures = signatures)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘Vision’ for signature ‘"Seurat"’

Can someone tell me what I did wrong/what went wrong?

Thanks,
Lies

**Comment by mattjones315** [comment]
Hi Lies, 

I suspect that your Seurat object was made using Seurat 3.X? If this is the case, VISION's Seurat constructor would fail. We built VISION before Seurat 3.X was released and so all of our Seurat-based constructors were predicated on the Seurat 2.X API. 

In light of Seurat's recent updates, we have implemented a constructor that supports Seurat 3.X. I've designed it so that VISION will automatically detect if Seurat 2.X or Seurat 3.X was used to construct the object you're passing in (or so I hope!). 

The changes are merged into our master branch, so if you're still wanting to use VISION I encourage you to reinstall from Github and try your analysis again. 

Thank you very much for raising this issue -- and please let me know if it works for you! 

Thanks,
Matt

**Comment by LVH10** [comment]
Hi Matt,

I used Seurat 3.0 to create the object. Reinstalling VISION from Github solved the problem.

Thanks,
Lies
