### ISSUE TITLE
Create new release to include Seurat 3 compatibility

### ISSUE THREAD

**Issue by tdido** [YosefLab/VISION#59]
I'm working on uploading vision to [bioconda](http://bioconda.github.io/), in order to integrate it into a pipeline of ours which handles its software through that repository.

We are using Seurat 3, and the latest release (1.1.0a) does not include the latest changes to make it compatible (according to #55).

Could I ask you to create a new release, so that it includes this and I can package it?

**Comment by deto** [comment]
Ok - I've created a release with all the master changes.

However, there's a v2.0 I've been working on that may be of interest to you.  It's basically been ready for a while but I just need to run some tests and merge it in - I'll see if I can take care of that today.

The release improves performance (avoid inflating sparse inputs, better use of memory when running parallel loops), and adds support for surface protein data (i.e. CITE-Seq), but the downside is that I had to make incompatible changes to the object structure (so you can't load v1.x objects and run 'viewResults' on them with the v2.0 code).  I try to avoid doing this as much as possible and hope that this is the last time this will happen - but the state of it was really a mess and a refactor was a long time coming.  Since this format will be the same moving forward, it might make more sense to use the 2.0 version in your pipeline instead.

**Comment by deto** [comment]
FYI, created the v2.0.0 release just now.  Let us know if you have any issues!

**Comment by tdido** [comment]
That's great, thank you. I'll create the package and it should be available in the next few days.

**Comment by deto** [comment]
Great - let me know and I'll add it as an option to the install
instructions!

- David

**Comment by tdido** [comment]
The conda package is ready. Installation with conda can be done be first setting up bioconda (in this way, you'd be able to seamlessly update):
```shell
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
conda install r-vision
```
Or you can just install the package:
```shell
conda install -c bioconda -c conda-forge r-vision
```
