### ISSUE TITLE
Different hallmark pathways are yielding the exact same results

### ISSUE THREAD

**Issue by xihuiyin** [YosefLab/VISION#91]
I am trying to run vision on my Seurat object. I have used the TNF signaling hallmark pathway, IFNg signaling hallmark pathway and the TGFb hallmark pathway and they are all giving me the exact same results for each signaling pathway. I think my code is running fine, but I'm not sure if this is a problem on VISION's side, or MSigDB, since their website was just recently down. 

Here is my code:

```
library(VISION)
signatures_tnf <- c("Mandy's datasets/msigdb/tnfa_nfkb.gmt")
tnf.all <- Vision(all.integrated, signatures = signatures_tnf)
tnf.all <- analyze(tnf.all)
viewResults(tnf.all)

signatures_tgfb <- c("Mandy's datasets/msigdb/tgfb.gmt")
tgfb.all <- Vision(all.integrated, signatures = signatures_tgfb)
tgfb.all <- analyze(tgfb.all)
viewResults(tgfb.all)


signatures_ifng <- c("Mandy's datasets/msigdb/ifng.gmt")
ifng.all <- Vision(all.integrated, signatures = signatures_ifng)
ifng.all <- analyze(ifng.all)
viewResults(ifng.all)
```

TNF:
![vision_tnf](https://user-images.githubusercontent.com/36392508/105667770-c64a6d00-5e90-11eb-8983-03dbc9b2b4a2.png)

IFNg:
![vision_ifng](https://user-images.githubusercontent.com/36392508/105667774-c9455d80-5e90-11eb-9279-0e0c67db0a65.png)

TGFb:
![tgfb](https://user-images.githubusercontent.com/36392508/105667780-cba7b780-5e90-11eb-8855-9ae1a5e72b3f.png)

**Comment by deto** [comment]
Hi xihuiyin - it looks like you are plotting the nFeature_RNA variable there.  That's a meta-data column that (I believe) Seurat adds that just shows the number of genes detected in each cell.  It is probably a part of your all.integrated object.  

In the visualizer, instead click on the name of the signature to plot its values.  Or, you can get this in the R environment by using the getSignatureScores on the output Vision object after analyze.  This returns a dataframe where each column contains the per-cell signature scores.

Another good thing to know - in .gmt files you can have multiple signatures in the same file.  Each line will be a different signature.  So you can join your three files together and just run Vision once instead of running for each signature.

**Comment by xihuiyin** [comment]
> Hi xihuiyin - it looks like you are plotting the nFeature_RNA variable there. That's a meta-data column that (I believe) Seurat adds that just shows the number of genes detected in each cell. It is probably a part of your all.integrated object.
> 
> In the visualizer, instead click on the name of the signature to plot its values. Or, you can get this in the R environment by using the getSignatureScores on the output Vision object after analyze. This returns a dataframe where each column contains the per-cell signature scores.
> 
> Another good thing to know - in .gmt files you can have multiple signatures in the same file. Each line will be a different signature. So you can join your three files together and just run Vision once instead of running for each signature.

This was very helpful. Thank you so much!
