### ISSUE TITLE
Signature Score Labelling metadata output

### ISSUE THREAD

**Issue by CisnerosFernandez** [YosefLab/VISION#96]
Hello, 

Thank you for your package, I wanted to use Vision to make comparison between ctr and treated samples but I am having doubts about the output. 

As I understand to look if a signature is more in one treatment or the other I should choose the metadata of the treatment in the signature score part and look there. Then there I have the local correlation (that I understand it does not depend on the metadata) and the other two boxes in the heatmap that should tell if the signature is more associated to one or the other treatment no?
Then I see in the images that the heatmap is colored differently and there is an asterisk of significance, however if I look for the AUC ROC and p-value of the two conditions is the same: 

![image](https://user-images.githubusercontent.com/82618802/122190302-fd4a0b00-ce91-11eb-93b2-d5a197e6c5fb.png)

![image](https://user-images.githubusercontent.com/82618802/122191401-01c2f380-ce93-11eb-81eb-d0c10ae8148d.png)

Thus my question is what is the meaning of the color?, and if there are differences or not? If the AUC ROC is calculated comparing one group vs all others (in my case treatment vs control) should not be the scores different?

**Comment by deto** [comment]
Hi Cisneros,

The scores should be the same since you only have two groups.  The score measure how well the signature scores differentiate between the groups.  The test statistic is the AUC of a classifier that tries to differentiate between the groups based on the score (this is directly related to the test statistic from the Wilcoxon rank-sums test too).  So for two groups Group 1 vs Group 2 is the same as Group 2 vs Group 1.  The sign isn't really captured in the hover text, but red is used to color the group that is higher, and blue is used to color the group that is lower (with the intensity based on the AUC).  

- David

**Comment by CisnerosFernandez** [comment]
Thank you very much for your kind answer.

**Comment by andynkili** [comment]
@deto, I am sorry but in the documentation 
<img width="1769" height="105" alt="Image" src="https://github.com/user-attachments/assets/e1fc2823-8e9a-4906-883f-287a502f8458" />
I a trying to understand what correlation is calculated (what VS what)? gene signature correlated to whatever metadata? and if so how categorical metadata is numerically represented in the calculation?

Best,
Andy

**Comment by andynkili** [comment]
@deto, I also took a look at the R code from github and the only mention of Pearson is the calculation between signature score and components in the latent space, but nothing regarding the correlation with metadata.

Also, how to intepret high AUROC and blue? I am trying to understand the signature score with respect to sample when there is high AUROC, significant pvalue => pathway still active but activity lower than other samples?

Best,
Andy
